/**
 * Sample data for local testing / demoing the Country -> State -> Recipes
 * browsing flow, search, and tag filters. Summaries are written by hand
 * here (rather than calling Claude during seeding) so the database is
 * useful for demoing immediately, even before an ANTHROPIC_API_KEY is
 * configured. Once the key is set, the "Regenerate summary" action on any
 * recipe will happily overwrite these with a fresh AI-written one.
 */
const sampleRecipes = [
  {
    recipeName: 'Kerala Fish Curry',
    country: 'India',
    state: 'Kerala',
    ingredients: [
      '500g kingfish, cut into steaks',
      '2 tbsp coconut oil',
      '1 onion, sliced',
      '2 tsp Kashmiri chilli powder',
      '1 tsp turmeric powder',
      '1 tbsp ginger-garlic paste',
      '10 curry leaves',
      '1 cup thick coconut milk',
      '2 pieces kudampuli (gambooge)',
      'Salt to taste',
    ],
    instructions: [
      'Soak the kudampuli pieces in a little warm water.',
      'Heat coconut oil in a clay pot and fry curry leaves and onions until soft.',
      'Add ginger-garlic paste, turmeric, and chilli powder; cook until fragrant.',
      'Add the fish, kudampuli with its soaking water, and enough water to half-cover the fish.',
      'Simmer gently for 12-15 minutes without stirring too much so the fish stays intact.',
      'Pour in the coconut milk, season with salt, and simmer for 5 more minutes before serving.',
    ],
    tags: ['seafood', 'spicy', 'savoury', 'dinner'],
    summary:
      'A tangy, fiery Kerala classic where firm kingfish simmers in a coconut-milk gravy soured with kudampuli. Curry leaves and Kashmiri chilli give it its signature deep red color and coastal aroma.',
    author: 'Lakshmi Menon',
  },
  {
    recipeName: 'Puttu with Kadala Curry',
    country: 'India',
    state: 'Kerala',
    ingredients: [
      '2 cups puttu podi (rice flour)',
      '1 cup grated coconut',
      'Salt to taste',
      '1 cup black chickpeas, soaked overnight',
      '1 onion, chopped',
      '2 tomatoes, chopped',
      '1 tsp garam masala',
      '1 tsp chilli powder',
    ],
    instructions: [
      'Mix puttu podi with a little salted water until crumbly, then layer with grated coconut in a puttu maker.',
      'Steam for 8-10 minutes until cooked through.',
      'Pressure-cook the chickpeas until soft.',
      'Saute onions and tomatoes, add spices, then add the cooked chickpeas with a splash of their stock.',
      'Simmer for 10 minutes and serve hot alongside the steamed puttu.',
    ],
    tags: ['breakfast', 'vegan', 'savoury'],
    summary:
      'A beloved Kerala breakfast pairing: delicate steamed rice-and-coconut cylinders served beside a hearty, spiced black chickpea curry. Comforting, filling, and entirely plant-based.',
    author: 'Anand Pillai',
  },
  {
    recipeName: 'Misal Pav',
    country: 'India',
    state: 'Maharashtra',
    ingredients: [
      '1 cup moth beans (matki), sprouted',
      '2 potatoes, boiled and cubed',
      '1 cup farsan (crunchy chickpea noodles)',
      '2 onions, finely chopped',
      '1 tbsp goda masala',
      '2 tbsp red chilli paste',
      '4 pav buns',
      'Lemon wedges and coriander to garnish',
    ],
    instructions: [
      'Pressure-cook the sprouted moth beans until just tender.',
      'Make a base gravy by sauteing onions with goda masala and chilli paste.',
      'Add the cooked beans and simmer until the gravy thickens slightly.',
      'Ladle into a bowl over boiled potato cubes, top generously with farsan and chopped onion.',
      'Serve immediately with pav, lemon, and coriander on the side.',
    ],
    tags: ['spicy', 'vegan', 'breakfast', 'snack'],
    summary:
      'Mumbai street food at its boldest: a fiery sprouted-moth-bean curry piled high with crunchy farsan and served with soft pav. Equal parts breakfast, snack, and badge of spice tolerance.',
    author: 'Priya Joshi',
  },
  {
    recipeName: 'Puran Poli',
    country: 'India',
    state: 'Maharashtra',
    ingredients: [
      '1 cup chana dal, boiled and mashed',
      '1 cup jaggery, grated',
      '1/2 tsp cardamom powder',
      '1/4 tsp nutmeg powder',
      '2 cups wheat flour',
      'Ghee for cooking',
    ],
    instructions: [
      'Cook the mashed chana dal with jaggery on low heat until it forms a thick, dry paste (puran).',
      'Stir in cardamom and nutmeg, then cool completely.',
      'Make a soft wheat dough and rest it for 20 minutes.',
      'Stuff small dough balls with the puran filling and roll out gently into flat discs.',
      'Cook on a hot griddle with ghee until golden spots appear on both sides.',
    ],
    tags: ['sweet', 'dessert', 'vegetarian'],
    summary:
      'A festive Maharashtrian stuffed flatbread filled with a fragrant jaggery-lentil filling scented with cardamom and nutmeg. Best eaten warm with a pool of ghee.',
    author: 'Priya Joshi',
  },
  {
    recipeName: 'Chettinad Chicken Curry',
    country: 'India',
    state: 'Tamil Nadu',
    ingredients: [
      '750g chicken, curry cut',
      '4 dried red chillies',
      '1 tbsp fennel seeds',
      '1 tsp peppercorns',
      '2 onions, sliced',
      '1 tbsp ginger-garlic paste',
      '2 tomatoes, chopped',
      '2 tbsp gingelly (sesame) oil',
      'Curry leaves',
    ],
    instructions: [
      'Dry roast dried chillies, fennel seeds, and peppercorns, then grind to a coarse powder.',
      'Heat gingelly oil and fry curry leaves and onions until deep golden.',
      'Add ginger-garlic paste and tomatoes, cooking until the oil separates.',
      'Stir in the ground spice mix and the chicken, coating well.',
      'Add a cup of water, cover, and simmer for 25 minutes until the chicken is tender and the gravy thickens.',
    ],
    tags: ['spicy', 'savoury', 'dinner'],
    summary:
      'A robustly spiced Chettinad classic built on a coarse roasted-pepper-and-fennel masala. Deep, dark, and unapologetically hot, finished with the nutty edge of gingelly oil.',
    author: 'Karthik Subramaniam',
  },
  {
    recipeName: 'Pondicherry Lemon Rice',
    country: 'India',
    state: 'Tamil Nadu',
    ingredients: [
      '2 cups cooked rice, cooled',
      '3 tbsp lemon juice',
      '2 tbsp peanuts',
      '1 tsp mustard seeds',
      '1 tsp split urad dal',
      '2 dried red chillies',
      'A pinch of turmeric',
      '2 tbsp oil',
      'Curry leaves',
    ],
    instructions: [
      'Heat oil and fry peanuts until golden, then set aside.',
      'In the same oil, splutter mustard seeds, urad dal, dried chillies, and curry leaves.',
      'Add turmeric and immediately add the cooled rice, mixing well.',
      'Turn off the heat, stir in the lemon juice, peanuts, and salt.',
      'Toss thoroughly so every grain is coated, then serve at room temperature.',
    ],
    tags: ['vegan', 'savoury', 'lunch', 'snack'],
    summary:
      'A bright, tangy rice dish from Tamil Nadu that turns leftover rice into something craveable. Crunchy peanuts and a mustard-curry-leaf tempering make every bite pop.',
    author: 'Karthik Subramaniam',
  },
  {
    recipeName: 'Tuscan Ribollita',
    country: 'Italy',
    state: 'Tuscany',
    ingredients: [
      '400g cannellini beans, cooked',
      '1/2 loaf stale rustic bread, torn',
      '1 bunch cavolo nero, chopped',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '1 onion, diced',
      '2 tbsp tomato paste',
      'Extra virgin olive oil',
      'Parmesan rind (optional)',
    ],
    instructions: [
      'Saute onion, carrot, and celery in olive oil until softened.',
      'Stir in tomato paste and cook for a minute, then add the beans and enough water or stock to cover generously.',
      'Add the parmesan rind if using and simmer for 20 minutes.',
      'Add the cavolo nero and torn bread, stirring until the bread breaks down and thickens the soup.',
      'Rest for 10 minutes off the heat, then serve with a generous drizzle of olive oil.',
    ],
    tags: ['vegetarian', 'savoury', 'dinner'],
    summary:
      'A rustic Tuscan soup born from frugality: stale bread, winter greens, and white beans simmered into something hearty and deeply comforting. Tastes even better the next day.',
    author: 'Giulia Rossi',
  },
  {
    recipeName: 'Sicilian Caponata',
    country: 'Italy',
    state: 'Sicily',
    ingredients: [
      '2 eggplants, cubed',
      '2 celery stalks, chopped',
      '1 onion, chopped',
      '200g tomatoes, chopped',
      '2 tbsp capers',
      '1/2 cup green olives, pitted',
      '3 tbsp red wine vinegar',
      '1 tbsp sugar',
      'Olive oil for frying',
    ],
    instructions: [
      'Fry the eggplant cubes in olive oil until golden, then drain on paper towels.',
      'In the same pan, soften celery and onion.',
      'Add tomatoes, capers, and olives, cooking until the tomatoes break down.',
      'Stir in vinegar and sugar, simmering until it forms a sweet-sour glaze.',
      'Fold the fried eggplant back in and cool to room temperature before serving.',
    ],
    tags: ['vegan', 'savoury', 'snack'],
    summary:
      'A sweet-and-sour Sicilian eggplant dish that balances briny capers and olives against a touch of sugar and vinegar. Traditionally served at room temperature as a starter.',
    author: 'Marco Bellini',
  },
  {
    recipeName: 'Hokkaido Miso Ramen',
    country: 'Japan',
    state: 'Hokkaido',
    ingredients: [
      '2 portions fresh ramen noodles',
      '4 cups pork or chicken stock',
      '3 tbsp miso paste',
      '1 tbsp grated garlic',
      '1 tbsp grated ginger',
      '1 cup corn kernels',
      '2 pats butter',
      '2 soft-boiled eggs',
      'Sliced pork belly (chashu)',
      'Scallions, sliced',
    ],
    instructions: [
      'Whisk miso paste, garlic, and ginger into the hot stock until dissolved.',
      'Cook the ramen noodles according to package instructions and drain well.',
      'Divide noodles between bowls and ladle the miso broth over them.',
      'Top each bowl with corn, a pat of butter, chashu, and a halved soft-boiled egg.',
      'Finish with scallions and serve immediately while the butter is still melting.',
    ],
    tags: ['savoury', 'dinner'],
    summary:
      "Hokkaido-style ramen turns up the richness with a garlicky miso broth, sweet corn, and a melting pat of butter. Hearty enough to stand up to the island's cold winters.",
    author: 'Haruto Sato',
  },
  {
    recipeName: 'Osaka Takoyaki',
    country: 'Japan',
    state: 'Kansai',
    ingredients: [
      '1 cup dashi stock',
      '1 cup flour',
      '1 egg',
      '200g boiled octopus, diced',
      '2 scallions, chopped',
      'Takoyaki sauce',
      'Mayonnaise',
      'Bonito flakes',
      'Dried seaweed powder (aonori)',
    ],
    instructions: [
      'Whisk dashi, flour, and egg into a smooth, thin batter.',
      'Heat a takoyaki pan and oil each mold generously.',
      'Fill molds with batter, drop in a piece of octopus and scallion into each.',
      'Once the edges set, use a skewer to rotate each ball a quarter turn repeatedly until fully round and golden.',
      'Plate and drizzle with takoyaki sauce and mayonnaise, then dust with bonito flakes and aonori.',
    ],
    tags: ['seafood', 'snack', 'savoury'],
    summary:
      "Osaka's favorite street snack: crisp-shelled, molten-centered batter balls studded with octopus. Topped with sweet-savory sauce, mayo, and a flurry of bonito flakes.",
    author: 'Yuki Tanaka',
  },
  {
    recipeName: 'Oaxacan Mole Negro',
    country: 'Mexico',
    state: 'Oaxaca',
    ingredients: [
      '6 dried chilhuacle negro chillies',
      '4 dried chipotle chillies',
      '1 plantain, sliced',
      '1/4 cup almonds',
      '2 tbsp sesame seeds',
      '1 tortilla, toasted',
      '50g dark chocolate',
      '1 onion, charred',
      '4 garlic cloves, charred',
      'Chicken stock',
    ],
    instructions: [
      'Toast and rehydrate the dried chillies in hot water.',
      'Fry the plantain, almonds, sesame seeds, and tortilla separately until deeply browned.',
      'Blend the chillies, fried ingredients, charred onion, and garlic with stock into a smooth paste.',
      'Simmer the paste in a pot, stirring frequently, for at least 45 minutes.',
      'Stir in the dark chocolate at the end until fully melted and glossy.',
    ],
    tags: ['spicy', 'savoury', 'dinner'],
    summary:
      "One of Mexico's most labor-intensive sauces, layering charred chillies, toasted nuts, and dark chocolate into a deep, smoky, slightly sweet mole. A celebration dish worth the effort.",
    author: 'Itzel Ramirez',
  },
  {
    recipeName: 'Provencal Ratatouille',
    country: 'France',
    state: 'Provence',
    ingredients: [
      '1 eggplant, sliced',
      '2 zucchini, sliced',
      '2 bell peppers, sliced',
      '4 tomatoes, sliced',
      '1 onion, sliced',
      '3 garlic cloves, minced',
      '2 tbsp herbes de Provence',
      'Olive oil',
    ],
    instructions: [
      'Saute onion and garlic in olive oil until fragrant.',
      'Spread the onion mixture in a baking dish, then arrange the sliced vegetables on top in alternating rows.',
      'Drizzle generously with olive oil and sprinkle with herbes de Provence and salt.',
      'Cover with foil and bake at 180C for 40 minutes.',
      'Uncover and bake for a further 15 minutes until the vegetables are tender and lightly caramelized.',
    ],
    tags: ['vegan', 'vegetarian', 'savoury', 'dinner'],
    summary:
      'A sun-drenched Provencal vegetable bake where eggplant, zucchini, and peppers slow-roast together under fragrant herbes de Provence. Simple ingredients, beautifully arranged.',
    author: 'Camille Dubois',
  },
  {
    recipeName: 'New Orleans Gumbo',
    country: 'USA',
    state: 'Louisiana',
    ingredients: [
      '1/2 cup flour',
      '1/2 cup oil',
      '1 onion, diced',
      '1 green bell pepper, diced',
      '2 celery stalks, diced',
      '500g andouille sausage, sliced',
      '500g shrimp, peeled',
      '1.5L chicken or seafood stock',
      '1 tsp cajun seasoning',
      'Cooked white rice, to serve',
    ],
    instructions: [
      'Whisk flour and oil together over medium-low heat, stirring constantly until it reaches a deep brown roux, about 25-30 minutes.',
      'Add onion, bell pepper, and celery to the roux and cook until softened.',
      'Stir in the sausage and cajun seasoning, then gradually whisk in the stock.',
      'Simmer for 45 minutes, stirring occasionally.',
      'Add the shrimp in the last 5 minutes of cooking and serve over rice.',
    ],
    tags: ['seafood', 'spicy', 'savoury', 'dinner'],
    summary:
      'A deeply savory Louisiana stew built on a patiently browned roux, loaded with andouille sausage and shrimp. The dark roux is what separates a true gumbo from an imitation.',
    author: 'Marcus Boudreaux',
  },
  {
    recipeName: 'Bangkok Mango Sticky Rice',
    country: 'Thailand',
    state: 'Bangkok',
    ingredients: [
      '1 cup glutinous rice, soaked overnight',
      '1 cup coconut milk',
      '3 tbsp sugar',
      '1/2 tsp salt',
      '2 ripe mangoes, sliced',
      '1 tbsp toasted mung beans, for garnish',
    ],
    instructions: [
      'Steam the soaked glutinous rice for about 25 minutes until translucent and tender.',
      'Warm the coconut milk with sugar and salt until dissolved, reserving a few tablespoons for drizzling.',
      'Pour most of the sweetened coconut milk over the hot rice and let it absorb for 10 minutes.',
      'Plate the rice alongside sliced mango.',
      'Drizzle with the reserved coconut milk and sprinkle with toasted mung beans.',
    ],
    tags: ['sweet', 'dessert', 'vegan'],
    summary:
      "Thailand's most iconic dessert pairs warm, coconut-soaked sticky rice with cool, ripe mango slices. A simple combination that nails sweet, salty, and creamy all at once.",
    author: 'Niran Suwan',
  },
];

module.exports = sampleRecipes;
